# Generated by Django 4.2 on 2024-10-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_section_alter_course_unique_together'),
        ('teacher', '0002_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherenrolled',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
