# Generated by Django 4.2 on 2024-10-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='qna_slug',
            field=models.SlugField(blank=True, max_length=264, unique=True),
        ),
    ]
