# Generated by Django 4.2 on 2024-10-27 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0002_alter_qna_qna_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('reply_date', models.DateTimeField(auto_now_add=True)),
                ('qna_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='qna.qna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
