# Generated by Django 4.2 on 2024-10-29 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0003_qnareply'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Liked', to='qna.qna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('qna', 'user')},
            },
        ),
    ]
