# Generated by Django 4.2 on 2024-10-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pic',
            field=models.ImageField(blank=True, upload_to='course_thumbnail'),
        ),
    ]
