# Generated by Django 4.2 on 2024-10-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'code', 'section')},
        ),
    ]
