# Generated by Django 4.2 on 2024-10-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursequiz_quizanswer_coursefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequiz',
            name='publish_status',
            field=models.BooleanField(default=False),
        ),
    ]
