# Generated by Django 4.2 on 2024-10-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursequiz_publish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
