# Generated by Django 4.2 on 2024-10-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursefile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
