# Generated by Django 4.2 on 2024-10-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courseassignment_assignmentuploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseassignment',
            name='question_text',
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='assignment_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='assignment_text',
            field=models.TextField(default='No assignment Related text provided'),
        ),
    ]
