# Generated by Django 4.2 on 2024-10-18 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_courseassignment_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentuploadfile',
            name='obtain_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentuploadfile',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentuploadfile',
            name='upload_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='due_date',
            field=models.DateTimeField(default='2024-11-17 15:00:22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
