# Generated by Django 4.2 on 2024-10-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_user'),
        ('courses', '0010_assignmentuploadfile_obtain_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentuploadfile',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_assignment', to='student.student'),
        ),
    ]
