# Generated by Django 4.2 on 2024-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_assignmentuploadfile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='question_mark',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
