# Generated by Django 4.2 on 2024-10-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_quizanswer_question_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequiz',
            name='time',
        ),
    ]
