# Generated by Django 4.2 on 2024-10-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_coursequiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequiz',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
