# Generated by Django 4.2 on 2024-10-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursequiz_duration_coursequiz_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequiz',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coursequiz',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coursequiz',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
