# Generated by Django 4.2 on 2024-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_coursequiz_duration_alter_coursequiz_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequiz',
            name='quiz_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
