# Generated by Django 4.2 on 2024-10-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_user'),
        ('courses', '0016_coursequiz_quiz_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtain_marks', models.PositiveIntegerField(null=True)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='courses.coursequiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_quiz_results', to='student.student')),
            ],
            options={
                'unique_together': {('quiz', 'student')},
            },
        ),
    ]
