# Generated by Django 4.2 on 2024-10-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_quizresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='obtain_marks',
            new_name='obtained_marks',
        ),
    ]
